### PR TITLE
7.0.3 update fixes

### PR DESCRIPTION
**Pull request by rambopfc**
fixed tooltips for items that were were shaking left and right, also updated a function to use new API changes in 7.0.

### CODE REVIEW

**Comment by freebaser** [comment]
thanks.

**Comment by fafaraway** [comment]
what about this tooltip from world map quest dot?
ddd

**Comment by rambopfc** [comment]
Hmm do those still wiggle? I'll have a look at it tomorrow. I didn't even think to check that

**Comment by rambopfc** [comment]
Those don't shake on my end. Everything on the map and quest / quest log looks normal to me.

**Pull request merged**
